### ISSUE TITLE
Unsure on category

### ISSUE THREAD

**Issue by Cordtus** [cosmos/awesome-cosmos#166]
Hey, I threw [this comprehensive key + wallet derivation tool](https://github.com/Cordtus/wallet_generator) together becasue this overall process seems pretty gate-kept. Not really sure where to place it in this repo though. I would say with `wallets` but it is not really a "wallet app" initself, although it also is.

**Comment by julienrbrt** [comment]
Hi, the tools > cli section seems the most appropriate.
